name: Code Vigorous
port: 8010
host: 0.0.0.0
url: http://code.v.igoro.us
markdown: kramdown
pygments: true
author: Dustin J. Mitchell
about: Dustin J. Mitchell
exclude: [ sandbox, .git, conversion ]
permalink: /posts/:year/:month/:title.html
urls:
    - text: github
      url: https://github.com/djmitche
    - text: mozillians
      url: https://mozillians.org/en-US/u/dustin/
    - text: email
      url: mailto:dustin@cs.uchicago.edu
